
language: python
python:
  - "3.7"      # current default Python on Travis CI
addons:
  firefox: "49.0.2"
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
  - tar -xzf geckodriver-v0.26.0-linux64.tar.gz
install:
  - pip install -r requirements.txt
script:
  - python testTravis.py
